package MusicShop.Instruments;

public enum InstrumentType {
    WIND("Pfffffffffft"),
    BRASS("PAAAAAAARP"),
    KEYS("Plinky Plonky"),
    PERCUSION("Bish, Bash, BOSH!"),
    STRING("SCCCCRreeeeeeeech"),
    GUITAR("Strum str-str-stummin");

    // value attribute
    private String noise;

    // InstrumentType constructor is Private and autogenerated.  But we need to add the value.
    InstrumentType(String noise) {
        this.noise = noise;
    }

    // Getter
    public String getNoise() {
        return this.noise;
    }

}
